# Generated by Django 6.0.2 on 2026-03-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_provider_tipo_provider_website'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='producto_nombre_libre',
            field=models.CharField(blank=True, help_text='Nombre del producto si no está en el catálogo (pedidos a tiendas de marca)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.product'),
        ),
    ]
