# Generated by Django 6.0.2 on 2026-03-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_purchaseorderitem_producto_nombre_libre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='origin_supplier',
            field=models.CharField(blank=True, help_text='Nombre del proveedor/marca de origen (para rutas ENTRADA)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='OC asociada (solo para rutas tipo ENTRADA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_routes', to='logistics.purchaseorder'),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida — Entrega a cliente'), ('ENTRADA', 'Entrada — Recepción de proveedor')], default='SALIDA', max_length=10),
        ),
    ]
