# Generated by Django 6.0.2 on 2026-03-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_client'),
        ('logistics', '0003_deliveryroute_origin_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sede donde se recibió o recibirá la mercancía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='companies.branch'),
        ),
    ]
