# Generated by Django 6.0.2 on 2026-03-28 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_order_provider_provider_latitud_provider_longitud'),
        ('logistics', '0004_purchaseorder_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='internal_order',
            field=models.ForeignKey(blank=True, help_text='Pedido Interno asociado (solo para rutas tipo INTERNO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_routes', to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida — Entrega a cliente'), ('ENTRADA', 'Entrada — Recepción de proveedor'), ('INTERNO', 'Traslado — Pedido Interno')], default='SALIDA', max_length=10),
        ),
    ]
