# Generated by Django 6.0.2 on 2026-03-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador General'), ('JEFE_INVENTARIO', 'Jefe de Inventario'), ('EMPLEADO', 'Empleado')], default='EMPLEADO', max_length=30),
        ),
    ]
