# Generated by Django 6.0.2 on 2026-03-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('BODEGA', 'Bodega'), ('ALMACEN', 'Almacén'), ('RECOGIDA', 'Recogida')], max_length=30, null=True, verbose_name='Cargo'),
        ),
    ]
