# Generated by Django 6.0.2 on 2026-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador General'), ('JEFE_INVENTARIO', 'Jefe de Inventario'), ('EMPLEADO', 'Empleado'), ('VENDEDOR', 'Vendedor / Asesor')], default='EMPLEADO', max_length=30),
        ),
    ]
