# Generated by Django 6.0.2 on 2026-03-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_passwordresettoken'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='max_stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_stock',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'company')},
        ),
    ]
