# Generated by Django 6.0.2 on 2026-03-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch'),
        ('inventory', '0004_inventory_branch_stockmovement_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.branch'),
        ),
    ]
