# Generated by Django 6.0.2 on 2026-03-19 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_client'),
        ('inventory', '0006_category_vida_util_meses_product_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='companies.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_type',
            field=models.CharField(choices=[('FISICA', 'Física'), ('ELECTRONICA', 'Electrónica')], default='FISICA', max_length=20),
        ),
    ]
