# Generated by Django 6.0.2 on 2026-03-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sale_client_sale_invoice_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date']},
        ),
    ]
