# Generated by Django 6.0.2 on 2026-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_sale_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vida_util_meses',
        ),
        migrations.AddField(
            model_name='category',
            name='vida_util_anios',
            field=models.IntegerField(default=0, help_text='Vida útil estimada en años'),
        ),
    ]
