# Generated by Django 6.0.2 on 2026-03-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_category_vida_util_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='tipo',
            field=models.CharField(choices=[('DISTRIBUIDOR', 'Distribuidor / Proveedor regular'), ('TIENDA_MARCA', 'Tienda de Marca Oficial')], default='DISTRIBUIDOR', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, help_text='Sitio web o tienda oficial', null=True),
        ),
    ]
