# Generated by Django 6.0.2 on 2026-03-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_provider_tipo_provider_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Proveedor origen del pedido. Si está vacío, es pedido interno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para el mapa', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para el mapa', max_digits=9, null=True),
        ),
    ]
