# Generated by Django 6.0.2 on 2026-04-06 17:00

from django.db import migrations
import uuid

def migrate_branches_to_warehouses(apps, schema_editor):
    Branch = apps.get_model('companies', 'Branch')
    Warehouse = apps.get_model('inventory', 'Warehouse')
    Inventory = apps.get_model('inventory', 'Inventory')
    StockMovement = apps.get_model('inventory', 'StockMovement')

    for branch in Branch.objects.all():
        warehouse, created = Warehouse.objects.get_or_create(
            branch=branch,
            name=f"{branch.name} - Bodega Principal",
            defaults={
                'id': uuid.uuid4(),
                'type': 'STORAGE',
                'is_active': True,
            }
        )
        
        for inv in Inventory.objects.filter(branch=branch, warehouse__isnull=True):
            inv.warehouse = warehouse
            inv.save()
            
        for mov in StockMovement.objects.filter(branch=branch, warehouse__isnull=True):
            mov.warehouse = warehouse
            mov.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_branch_alter_stockmovement_branch_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_branches_to_warehouses, migrations.RunPython.noop),
    ]
