# Generated by Django 6.0.2 on 2026-04-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_migrate_warehouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='branch',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.warehouse'),
        ),
    ]
