# Generated by Django 6.0.2 on 2026-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para el mapa', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para el mapa', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para el mapa', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para el mapa', max_digits=9, null=True),
        ),
    ]
